require("vis")
require("plugins/cursors")
require("plugins/tables")
require("plugins/title")
require("plugins/vis-lspc")
require("plugins/complete-filename")
require("plugins/go-format")

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
	vis:command("set theme default")
	vis:command("set relativenumber")
	vis:command("set showtabs")
	vis:command("set autoindent")
	vis:command("set tabwidth 4")
end)
