add_newline = true
format = "$directory$git_branch$git_status$python\n$character\n"

[directory]
format = "[$path]($style)"
style = "bold"
truncation_length = 3

[git_branch]
format = "[ |   ($branch)]($style)"
style = "bold"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold"
